### ISSUE TITLE
About short reads: insert size and type

### ISSUE THREAD

**Issue by ptranvan** [holtjma/fmlrc#16]
Hi,

In order to correct my long reads, I have short reads of different insert size and different types (paired end and mate pair). 

1) How is it handle by the program ?

For example for the 1st part `Building the short-read BWT` with this guide: https://github.com/holtjma/fmlrc/wiki/Converting-to-the-fmlrc-RLE-BWT-format 

2) Should I just catenate everything into a single file (so transforming my paired to single reads). Can we use only paired end or also mate pairs ?

3) What is the optimal coverage for long reads and short reads ?

Thanks a lot for your help.

**Comment by holtjma** [comment]
Paired-end information is not actually stored anywhere inside the BWT, only string sequences.  Any paired reads are effectively reduced to single-end reads for the purpose of constructing the BWT and FMLRC then only uses the string sequences for correction.

If you have a bunch of fastq files, you would basically `cat` or `gunzip -c` them all together in that first step and everything would fall into place (see [example](https://github.com/holtjma/fmlrc/blob/77dde49ba890777ccc3bfcaf8075856cdc54b7ca/example/run_example.sh#L39) with ecoli paired end).

For read correction, the coverage of long reads doesn't matter (since that's what you're correcting), but you want "sufficient" short-read coverage that the correction algorithm of FMLRC considers the k-mers to be solid.  The default absolute minimum k-mer count is 5, and the default dynamic count is 10% of the median counts along the long-read.

**Comment by ptranvan** [comment]
Thanks.

I dont't have too much resources so I guess using more reads require more memory. 

For short reads coverage, is 50X is a "sufficient" amount ?

**Comment by holtjma** [comment]
More short reads will use more memory during the FMLRC steps, increasing long reads will not impact the memory usage (but will increase run-time of course).

For a diploid organism, I would expect 50X to be enough yes.
