### ISSUE TITLE
FMLRC (Or Ropebwt) not working correctly

### ISSUE THREAD

**Issue by jaworskicoline** [holtjma/fmlrc#4]
Hello,
I am trying to run the FMLRC program on Drosophila melanogaster data. Since not all the shortreads are exactly 100bp (some are shorter due to trimming, and some a re a few bases more), I am using Ropebswt2. I had to change the command line as compared to the guidelines, because the numbers for ($, A, G, C, T, N) were incoherent:
$ awk 'NR % 4 == 2' Dmel_data/Shortreads/Short_*_trimmed.fastq | sort | ropebwt2 -LR | tr NT TN | msbwt convert ./msbwt6

The info from Ropebwt performance is:
****
[M::main_ropebwt2] inserted 10415295755 symbols in 764.260 sec, 1747.782 CPU sec
[M::main_ropebwt2] inserted 6587840007 symbols in 443.204 sec, 1198.430 CPU sec
[M::main_ropebwt2] constructed FM-index in 1346.672 sec, 3046.289 CPU sec
[M::main_ropebwt2] symbol counts: ($, A, C, G, T, N) = (171420988, 5079437921, 3339642692, 3349827151, 5058703850, 4103160)
[M::main] Version: r187
[M::main] CMD: ropebwt2 -LR
[M::main] Real time: 4022.990 sec; CPU: 3399.186 sec
****
AND
****
[2017-08-25 12:29:16] INFO: Input: stdin
[2017-08-25 12:29:16] INFO: Output: ./msbwt6
[2017-08-25 12:29:16] INFO: Beginning conversion...
[2017-08-25 13:36:01] INFO: Finished conversion.
****
It looks to me that Ropebwt2 reads a file containing the correct number of sequences ($=171420988, and #G~#C /#A~#T (which was not the case with the added "tr NT TN").
I do have a 2Go file in msbwt6 (comp_msbwt.npy), but when I run FMLRC as recommended ($ fmlrc -p 14 -V ./msbwt6/comp_msbwt.npy Dmel_data/PacBio_reads/Pacreads.fasta ./Dmel_PB_corrected_FMLRC6.fasta) on this file, the . fasta output looks incoherent, here is the had of the output file:
***
$ head Dmel_PB_corrected_FMLRC6.fasta 
Usage:   fmlrc [options] <comp_msbwt.npy> <long_reads.fa> <corrected_reads.fa>
NNTNNNNNNNNNNNNNNNNNNNNTNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNTNNNNNNNNNNNNNNNNANNNNNNTNNNNNNNNNNNNNNTNNN
NNNANNNNNNNNNNNNNNNNNNANNTNNNNNNNNNNNNNNNNNNNTNNNN
NANGNNNNNNNNNNNNNNNNNANNTNNNNNNNNNTNNNNNNNNNNNNGNN
NNANNNNNNNNNNNNNNNNTNNNNNNNNNNNNNNCNNNNCTNNNNTNNNA
NNNNNNNNNNNNNNNNTNNNNNNNNNNNNNNNANNTNNNTANTNNNTNNN
NNNANNTNNNNNNNNNNNNNNNNNNTNNNNNNNNNNNNNNNANNTNNNNN
NNNTNNNNNNANNTNNNNNNNNNNNNNNNNNNNNNNNNNNNNTNNNNANN
NNNTNNNNNNNNNNCNNNTNTNNCNNNNNNNNANNATNNNNNNANNTNNN
****
So I have several questions to figure out how to debug this:

1/ What are the accepted formats for input data ?
2/ can we feed two different files as input (ie, 1.fastq and 2.fastq, for paired end reads) ?
3/ How can we know whether the Ropebswt2 step versus the FMLRC step went wrong, ie how can I validate the comp_msbwt.npy file ?

Note than even in verbose mode, FMLRC produces scarce info on what happens.
Thank you very much for your help.
Best regards,
Coline

**Comment by holtjma** [comment]
Coline,

So let me first address what I believe the problem is.  First, **both** ```tr NT TN``` commands are absolutely necessary.  The reason is that msbwt and ropebwt2 use alphabets that are ordered differently.  Specifically, msbwt using lexicographic ordering ($<A<C<G<N<T) whereas ropebwt2 has a different order ($<A<C<G<T<N).  Because of this difference, the first ```tr NT TN``` is translating from lexicographic order to ropebwt2 order.  Then ropebwt2 runs and will appear to have a large number of 'N' symbols and very few 'T' symbols, but this is expected due to the alphabet change.  The second ```tr NT TN``` will translate from ropebwt2 order back into the lexicographic order expected by msbwt (and fmlrc).

I strongly believe the second symptom (the large number of 'N' symbols in your output) is caused by the fact that you are replacing all 'T' symbols with 'N's because you only ran ```tr NT TN``` once.  I recommend running the command _exactly_ as listed on the [msbwt conversion wiki](https://github.com/holtjma/msbwt/wiki/Converting-to-msbwt's-RLE-format).  Given your above information, it should look like this:
```
awk 'NR % 4 == 2' Dmel_data/Shortreads/Short_*_trimmed.fastq | sort | tr NT TN | ropebwt2 -LR | tr NT TN | msbwt convert ./msbwt6
```

For your follow up questions:

1. ropebwt2 expects one read per line, all commands before that are just tricks to get to that format with an alphabet and string order that is expected in msbwt.  fmlrc needs the comp_msbwt.npy file that will be created by the above command and a FASTA file for the long reads (other formats are not supported at this time).
2. There is no support for paired end information in the msbwt construction.  You can absolutely feed multiple files into the the sort (as you are currently doing with awk), but the are treated as single-end reads.
3. If you know how many times each symbol occurs in your reads, you can do some sanity checks using msbwt queries.  [This page](https://github.com/holtjma/msbwt/wiki/Queries-with-the-Command-Line-Interface) will tell you how to query via command line and [this page](https://github.com/holtjma/msbwt/wiki/Queries-with-the-Python-API) via python2.7.  Typically, I check that the number of reads (the number of '$' symbols) matches my expected and that A\~T, C\~G, and there are few 'N' values in the final msbwt.

Let me know if you have any more questions and I'll be glad to help!

**Comment by jaworskicoline** [comment]
Hi, thank you for your answer,
So, to make sure I retried it with the exact command you suggested:
$ module load python/2/2.7.11
$ awk 'NR % 4 == 2' Dmel_data/Shortreads/Short_*_trimmed.fastq | sort | tr NT TN | ropebwt2 -LR | tr NT TN | msbwt convert ./msbwt8

I do get a 2G  comp_msbwt.npy file, and the info message from Ropebwt look fine:
*****
[M::main_ropebwt2] inserted 10415295755 symbols in 689.381 sec, 1710.703 CPU sec
[M::main_ropebwt2] inserted 6587840007 symbols in 474.237 sec, 1251.791 CPU sec
[M::main_ropebwt2] constructed FM-index in 1466.845 sec, 3216.144 CPU sec
[M::main_ropebwt2] symbol counts: ($, A, C, G, T, N) = (171420988, 5079437921, 3339642692, 3349827151, 4103160, 5058703850)
[M::main] Version: r187
[M::main] CMD: ropebwt2 -LR
[M::main] Real time: 3596.272 sec; CPU: 3575.474 sec
*****

But, the output from FMLRC is still not fine. Here is the info message from FMLRC step:
****
loaded bwt with 2063456295 compressed values
0: avg change 0.003906 -> 0.003906
Finished processing reads [0, 1)
****

Therefore, I still don't get what gets wrong, whether it's Ropebwt/msbwt step or FMLRC step, and how can I fix it. What are your thoughts ?
Thank you very much.
Best regards,
Coline

**Comment by holtjma** [comment]
Can you tell me the command you are running?  It looks like your dataset only had one read in your long read file

**Comment by jaworskicoline** [comment]
If I interpret well, Ropbewt sees 171420988 reads ($), correct ?
Or, Ropebwt is working well, but not msbwt ??
****
command for first step is:
$ module load python/2/2.7.11
$ awk 'NR % 4 == 2' Dmel_data/Shortreads/Short_*_trimmed.fastq | sort | tr NT TN | ropebwt2 -LR | tr NT TN | msbwt convert ./msbwt8

Command for second step is:
$ fmlrc -p 14 -V ./msbwt8/comp_msbwt.npy Dmel_data/PacBio_reads/Pacreads.fasta ./Dmel_PB_corrected_FMLRC8.fasta

**Comment by holtjma** [comment]
There are a couple of things you can try.  I think the issue is likely your input long read file.  Fmlrc seems to only be finding a single read in the file, which is unusual.  If you can validate that it is in a correct FASTA format, that's how I would start.  Alternatively, if there really is only a single read in the file, it could be that fmlrc failed to correct it (we see this in real data, where there just isn't a kmer in the BWT for fmlrc to use as an anchor).

If you're worried about the BWT, you can validate the BWT construction using the "msbwt query" option followed by single character k-mers just to validate that the symbol counts match your expected counts from the short reads.  Based on your earlier output, the BWT should be constructed correctly though.

If the data you're using is public, I can also take a look at the files if you link the URLs for me.

**Comment by holtjma** [comment]
Coline,

I wrote up a quick start guide using publicly available test data that we've used before.  I just tested the full script from start to finish and it works locally on my machine, so you may want to test that out to see if it's an install issue or a data issue.

Here's a link to the new wiki page on the [quick start](https://github.com/holtjma/fmlrc/wiki/Quick-start-test).

Matt

**Comment by jaworskicoline** [comment]
You were right, thank you so much ! The content of my long_reads.fasta file had been erased by something else, not even reads, and I did not know it. So obviously, the FMLRC could not correct reads because there were none. Thank you for pointing that out ! You might want to add a warning output checking for the content of input files in the program (eg something saying that the input files are not readable, not in correct format, etc etc..), or at note on the wiki that we should check on the number of reads processed by FMLRC. Thank you very much !
Best,
Coline

**Comment by holtjma** [comment]
Great, glad you got it working! In the past, we've relied on other QC checks so we don't bog down FMLRC with additional checks, but I'll see if I can think of something light-weight we can do to point users in that direction.  Let me know if you have any more issues!
